/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppUserCreateDto { 
    username: string;
    password: string;
    email: string;
    address?: string;
    phone?: string;
    metadata?: string;
    expired?: boolean;
    locked?: boolean;
    credentialsExpired?: boolean;
    disabled?: boolean;
    roles?: Array<string>;
    google?: boolean;
    facebook?: boolean;
    gitHub?: boolean;
    microsoft?: boolean;
}

