/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppUserUpdateDto { 
    username?: string;
    email?: string;
    password?: string;
    name?: string;
    surname1?: string;
    surname2?: string;
    address?: string;
    phone?: string;
    metadata?: string;
    expired?: boolean;
    locked?: boolean;
    credentialsExpired?: boolean;
    disabled?: boolean;
    roles?: Set<string>;
    microsoft?: boolean;
    facebook?: boolean;
    google?: boolean;
    gitHub?: boolean;
}

