/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientCreateDto { 
    clientId?: string;
    clientSecret?: string;
    clientName?: string;
    authenticationMethods?: Set<string>;
    authorizationGrantTypes?: Set<string>;
    redirectUris?: Set<string>;
    postLogoutRedirectUris?: Set<string>;
    scopes?: Set<string>;
    requireProofKey?: boolean;
}

