/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageable-object';
import { PermissionResponseDto } from './permission-response-dto';
import { SortObject } from './sort-object';


export interface PagePermissionResponseDto { 
    totalPages?: number;
    totalElements?: number;
    size?: number;
    content?: Array<PermissionResponseDto>;
    number?: number;
    sort?: SortObject;
    numberOfElements?: number;
    first?: boolean;
    last?: boolean;
    pageable?: PageableObject;
    empty?: boolean;
}

