/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PermissionResponseDto { 
    id?: string;
    name?: string;
    description?: string;
    active?: boolean;
    createdAt?: string;
    updatedAt?: string;
}

