/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleCreateDto { 
    name?: string;
    description?: string;
    permissions?: Set<string>;
    active?: boolean;
}

