/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppResponseDto } from './dtos/models';
import { ClientCreateDto } from './dtos/models';
import { ClientUpdateDto } from './dtos/models';
import { PageClientResponseDto } from './dtos/models';


import { Configuration }                                     from '../generated/auth-api/configuration';


export interface CreateRequestParams {
    clientCreateDto: ClientCreateDto;
}

export interface DeleteClientRequestParams {
    clientId: string;
}

export interface GetAll3RequestParams {
    clientName?: string;
    page?: number;
    size?: number;
}

export interface Update3RequestParams {
    clientUpdateDto: ClientUpdateDto;
}


export interface ClientControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/client
* @param requestParameters
     */
    create(requestParameters: CreateRequestParams, extraHttpRequestParams?: any): Observable<AppResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/v1/client/{clientId}
* @param requestParameters
     */
    deleteClient(requestParameters: DeleteClientRequestParams, extraHttpRequestParams?: any): Observable<AppResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/client/all
* @param requestParameters
     */
    getAll3(requestParameters: GetAll3RequestParams, extraHttpRequestParams?: any): Observable<PageClientResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/v1/client
* @param requestParameters
     */
    update3(requestParameters: Update3RequestParams, extraHttpRequestParams?: any): Observable<AppResponseDto>;

}
