/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppResponseDto } from './dtos/models';
import { PagePermissionResponseDto } from './dtos/models';
import { PermissionCreateDto } from './dtos/models';
import { PermissionResponseDto } from './dtos/models';
import { PermissionUpdateDto } from './dtos/models';


import { Configuration }                                     from '../generated/auth-api/configuration';


export interface Create3RequestParams {
    permissionCreateDto: PermissionCreateDto;
}

export interface Delete2RequestParams {
    id: string;
}

export interface DeleteBatchRequestParams {
    requestBody: Array<string>;
}

export interface GetAll2RequestParams {
    search?: string;
    page?: number;
    size?: number;
}

export interface GetById2RequestParams {
    id: string;
}

export interface Update2RequestParams {
    id: string;
    permissionUpdateDto: PermissionUpdateDto;
}


export interface PermissionControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/permission
* @param requestParameters
     */
    create3(requestParameters: Create3RequestParams, extraHttpRequestParams?: any): Observable<AppResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/v1/permission/{id}
* @param requestParameters
     */
    delete2(requestParameters: Delete2RequestParams, extraHttpRequestParams?: any): Observable<AppResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/v1/permission/batch
* @param requestParameters
     */
    deleteBatch(requestParameters: DeleteBatchRequestParams, extraHttpRequestParams?: any): Observable<AppResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/permission/all
* @param requestParameters
     */
    getAll2(requestParameters: GetAll2RequestParams, extraHttpRequestParams?: any): Observable<PagePermissionResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/permission/{id}
* @param requestParameters
     */
    getById2(requestParameters: GetById2RequestParams, extraHttpRequestParams?: any): Observable<PermissionResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/v1/permission/{id}
* @param requestParameters
     */
    update2(requestParameters: Update2RequestParams, extraHttpRequestParams?: any): Observable<AppResponseDto>;

}
