/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppResponseDto } from './dtos/models';
import { PageRoleResponseDto } from './dtos/models';
import { RoleCreateDto } from './dtos/models';
import { RoleResponseDto } from './dtos/models';
import { RoleUpdateDto } from './dtos/models';


import { Configuration }                                     from '../generated/auth-api/configuration';


export interface Create2RequestParams {
    roleCreateDto: RoleCreateDto;
}

export interface Delete1RequestParams {
    id: string;
}

export interface GetAll1RequestParams {
    search?: string;
    page?: number;
    size?: number;
}

export interface GetById1RequestParams {
    id: string;
}

export interface Update1RequestParams {
    id: string;
    roleUpdateDto: RoleUpdateDto;
}


export interface RoleControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/role
* @param requestParameters
     */
    create2(requestParameters: Create2RequestParams, extraHttpRequestParams?: any): Observable<AppResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/v1/role/{id}
* @param requestParameters
     */
    delete1(requestParameters: Delete1RequestParams, extraHttpRequestParams?: any): Observable<AppResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/role/all
* @param requestParameters
     */
    getAll1(requestParameters: GetAll1RequestParams, extraHttpRequestParams?: any): Observable<PageRoleResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/role/{id}
* @param requestParameters
     */
    getById1(requestParameters: GetById1RequestParams, extraHttpRequestParams?: any): Observable<RoleResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/v1/role/{id}
* @param requestParameters
     */
    update1(requestParameters: Update1RequestParams, extraHttpRequestParams?: any): Observable<AppResponseDto>;

}
