/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SubscriptionUsers } from './dtos/models';


import { Configuration }                                     from '../generated/subscription-api/configuration';


export interface Create1RequestParams {
    subscriptionUsers: SubscriptionUsers;
}

export interface Delete1RequestParams {
    id: string;
}

export interface GetAll1RequestParams {
    subscriptionId?: string;
    userId?: string;
}

export interface GetById1RequestParams {
    id: string;
}


export interface SubscriptionUsersControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/subscription-users
* @param requestParameters
     */
    create1(requestParameters: Create1RequestParams, extraHttpRequestParams?: any): Observable<SubscriptionUsers>;

    /**
     * 
     * 
     * @endpoint delete /api/v1/subscription-users/{id}
* @param requestParameters
     */
    delete1(requestParameters: Delete1RequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/v1/subscription-users
* @param requestParameters
     */
    getAll1(requestParameters: GetAll1RequestParams, extraHttpRequestParams?: any): Observable<Array<SubscriptionUsers>>;

    /**
     * 
     * 
     * @endpoint get /api/v1/subscription-users/{id}
* @param requestParameters
     */
    getById1(requestParameters: GetById1RequestParams, extraHttpRequestParams?: any): Observable<SubscriptionUsers>;

}
