/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Subscription } from './dtos/models';


import { Configuration }                                     from '../generated/subscription-api/configuration';


export interface DeleteRequestParams {
    id: string;
}

export interface CreateRequestParams {
    subscription: Subscription;
}

export interface GetByIdRequestParams {
    id: string;
}

export interface UpdateRequestParams {
    id: string;
    subscription: Subscription;
}


export interface SubscriptionControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint delete /api/v1/subscriptions/{id}
* @param requestParameters
     */
    _delete(requestParameters: DeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/v1/subscriptions
* @param requestParameters
     */
    create(requestParameters: CreateRequestParams, extraHttpRequestParams?: any): Observable<Subscription>;

    /**
     * 
     * 
     * @endpoint get /api/v1/subscriptions
*/
    getAll(extraHttpRequestParams?: any): Observable<Array<Subscription>>;

    /**
     * 
     * 
     * @endpoint get /api/v1/subscriptions/{id}
* @param requestParameters
     */
    getById(requestParameters: GetByIdRequestParams, extraHttpRequestParams?: any): Observable<Subscription>;

    /**
     * 
     * 
     * @endpoint put /api/v1/subscriptions/{id}
* @param requestParameters
     */
    update(requestParameters: UpdateRequestParams, extraHttpRequestParams?: any): Observable<Subscription>;

}
