/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppResponseDto } from './dtos/models';
import { AppUserCreateDto } from './dtos/models';
import { AppUserResponseDto } from './dtos/models';
import { AppUserUpdateDto } from './dtos/models';
import { PageAppUserResponseDto } from './dtos/models';


import { Configuration }                                     from '../generated/auth-api/configuration';


export interface DeleteRequestParams {
    id: string;
}

export interface Create1RequestParams {
    appUserCreateDto: AppUserCreateDto;
}

export interface GetAllRequestParams {
    search?: string;
    page?: number;
    size?: number;
}

export interface GetByIdRequestParams {
    id: string;
}

export interface UpdateRequestParams {
    id: string;
    appUserUpdateDto: AppUserUpdateDto;
}


export interface UserControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint delete /api/v1/user/{id}
* @param requestParameters
     */
    _delete(requestParameters: DeleteRequestParams, extraHttpRequestParams?: any): Observable<AppResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/v1/user
* @param requestParameters
     */
    create1(requestParameters: Create1RequestParams, extraHttpRequestParams?: any): Observable<AppResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/user/all
* @param requestParameters
     */
    getAll(requestParameters: GetAllRequestParams, extraHttpRequestParams?: any): Observable<PageAppUserResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/user/{id}
* @param requestParameters
     */
    getById(requestParameters: GetByIdRequestParams, extraHttpRequestParams?: any): Observable<AppUserResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/v1/user/{id}
* @param requestParameters
     */
    update(requestParameters: UpdateRequestParams, extraHttpRequestParams?: any): Observable<AppResponseDto>;

}
